run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - govet
    - unused
linters-settings:
  gofmt:
    simplify: true
  golint:
    min-confidence: 0.8
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
version: 2